### ISSUE TITLE
ddrcharttool.py: .sm -> .ssq/.csq conversion is buggy with stops?

### ISSUE THREAD

**Issue by infinitephantasm** [987123879113/gobbletools#2]
when using ddrcharttool.py, the overall ability to convert stops when converting a .sm to the .ssq or .csq format seems to vary in actual working form. sometimes it'll convert them properly, and then sometimes it just...won't? i'm not exactly sure why this happens.

as an example, here is VerTex^2 from ITG2's stops before conversion to a .csq:
![image](https://user-images.githubusercontent.com/23409983/117895063-3edc0a80-b283-11eb-82cf-1d187680c024.png)

then, after conversion, converted back to .sm:
![image](https://user-images.githubusercontent.com/23409983/117895106-4d2a2680-b283-11eb-8b60-10e4f5e99f57.png)

all but 2 of them were left unadded, leaving the chart off-track from its original.
i know this isn't going to be much of a high priority issue, since you probably have many more important things to worry about, but i'll submit this issue anyways just to keep it noted.

**Comment by 987123879113** [comment]
Confirmed the issue. It looks like it's writing bad BPM values so those BPM changes are in there, it's just saying to go to close to 550 bpm instead of 0. 😇 

I'll see about fixing it.

**Comment by 987123879113** [comment]
I think the cause is that Vertex^2 does something weird with the BPMs.

The stops that work have the stop and next BPM on the same beat. For example, stops and starts again on beat 190.
The stops that don't work have the stop and next BPM on different beats. For example, stops on 156 and starts again on 158.

It feels like this is kind of an abusive way to do stops because it doesn't seem like you should be able to progress past beat 156 when the BPM is 0. I can try to add a hack in for this but tbh it doesn't feel right (but obviously Stepmania seems to allow it).

**Comment by 987123879113** [comment]
It's kinda hacky but I fixed it. https://github.com/987123879113/gobbletools/commit/e59534fe218c96130d6a07c3145c8017b70b7f5b
